### ISSUE TITLE
switch status doesnt update when I press the real button hardware. I have to refresh browser to get new status

### ISSUE THREAD

**Issue by raditv** [knowthelist/fhem-tablet-ui#36]

**Comment by knowthelist** [comment]
Please check it again now. I pushed an update

**Comment by raditv** [comment]
still the same, here is my screen capture while I press hardware button
http://youtu.be/LF_MNf_No_w
